import React,{useMemo,useState} from 'react';
import {createRoot} from 'react-dom/client';
import {Search,MoreVertical,Paperclip,Smile,Mic,Send,CheckCheck,Phone,Video,ArrowLeft,Plus,Users,Settings,MessageCircle,Camera,Image as ImageIcon} from 'lucide-react';
import './styles.css';

const chats=[
 {id:1,name:'Arun Kumar',avatar:'https://i.pravatar.cc/96?img=12',last:'Bro, project ready?',time:'11:42 AM',unread:2,online:true},
 {id:2,name:'Priya',avatar:'https://i.pravatar.cc/96?img=47',last:'See you tomorrow ❤️',time:'10:18 AM',unread:0,online:true},
 {id:3,name:'AgriBot Team',avatar:'https://i.pravatar.cc/96?img=32',last:'Gokul: Sensor update pushed',time:'9:55 AM',unread:5,group:true},
 {id:4,name:'Vignesh',avatar:'https://i.pravatar.cc/96?img=68',last:'👍',time:'Yesterday',unread:0,online:false},
 {id:5,name:'College Group',avatar:'https://i.pravatar.cc/96?img=56',last:'Rahul: Tomorrow 9 AM',time:'Yesterday',unread:18,group:true}
];
const initial={1:[['in','Hey bro! 👋','11:38 AM'],['out','Hey! What’s up?','11:39 AM'],['in','Bro, project ready?','11:42 AM']],2:[['in','See you tomorrow ❤️','10:18 AM']],3:[['in','Sensor update pushed','9:54 AM'],['out','Great! I’ll check it.','9:55 AM']],4:[['in','👍','Yesterday']],5:[['in','Tomorrow 9 AM','Yesterday']]};
function App(){const [selected,setSelected]=useState(1);const [query,setQuery]=useState('');const [text,setText]=useState('');const [messages,setMessages]=useState(initial);const [mobileChat,setMobileChat]=useState(false);const [dark,setDark]=useState(true);const active=chats.find(c=>c.id===selected);const filtered=useMemo(()=>chats.filter(c=>c.name.toLowerCase().includes(query.toLowerCase())),[query]);
 const send=()=>{if(!text.trim())return;setMessages(m=>({...m,[selected]:[...(m[selected]||[]),['out',text.trim(),'now']]}));setText('')};
 return <div className={dark?'app dark':'app'}><aside className="sidebar"><header className="side-head"><b>ChatWave</b><div><button title="New chat"><Plus/></button><button><MoreVertical/></button></div></header><div className="search"><Search size={17}/><input placeholder="Search or start new chat" value={query} onChange={e=>setQuery(e.target.value)}/></div><div className="tabs"><button className="active">All</button><button>Unread</button><button>Groups</button></div><div className="chat-list">{filtered.map(c=><button className={'chat '+(selected===c.id?'selected':'')} key={c.id} onClick={()=>{setSelected(c.id);setMobileChat(true)}}><img src={c.avatar}/><span className="chat-info"><strong>{c.name}</strong><small>{c.last}</small></span><span className="chat-meta"><small>{c.time}</small>{c.unread>0&&<em>{c.unread}</em>}</span></button>)}</div><footer><button><Users/><span>Communities</span></button><button><Settings/><span>Settings</span></button></footer></aside><main className={'conversation '+(mobileChat?'show-mobile':'')}><header className="conv-head"><button className="back" onClick={()=>setMobileChat(false)}><ArrowLeft/></button><img src={active.avatar}/><div><strong>{active.name}</strong><small>{active.group?'5 members':active.online?'online':'last seen recently'}</small></div><div className="conv-actions"><button><Video/></button><button><Phone/></button><button><Search/></button><button><MoreVertical/></button></div></header><section className="messages">{(messages[selected]||[]).map((m,i)=><div className={'bubble-row '+m[0]} key={i}><div className="bubble"><span>{m[1]}</span><small>{m[2]} {m[0]==='out'&&<CheckCheck size={14}/>}</small></div></div>)}<div className="secure">🔒 Messages are end-to-end encrypted in this demo UI.</div></section><div className="composer"><button><Smile/></button><button><Paperclip/></button><input value={text} onChange={e=>setText(e.target.value)} onKeyDown={e=>e.key==='Enter'&&send()} placeholder="Type a message"/>{text?<button className="send" onClick={send}><Send/></button>:<button><Mic/></button>}</div></main><div className="welcome"><MessageCircle size={70}/><h1>ChatWave</h1><p>Private, fast messaging for your everyday conversations.</p><span>Built as an independent WhatsApp-style clone.</span></div></div>}

createRoot(document.getElementById('root')).render(<App/>);
